/**
 * Community-curated list of suspected AI-generated music artists on Spotify.
 * Sources: Reddit compilations, GitHub spotify-ai-blocker, community reports.
 *
 * Names are stored lowercase for case-insensitive matching.
 * This list should be regularly updated as new AI artists are discovered.
 */

const AI_ARTIST_NAMES: string[] = [
  // ── From Reddit compilations & community reports ──────────────
  "mc-dg",
  "voiceless",
  "glorb",
  "ada lee",
  "adriana",
  "aiva",
  "aimi",
  "airis",
  "amper music",
  "andy mineo ai",
  "anna indiana",
  "artificial dj",
  "auranova",
  "auto-tune king",
  "beat sage",
  "bella ai",
  "bloom",
  "botnik studios",
  "byte beats",
  "celestia nova",
  "chirp",
  "circuit breaker",
  "coda",
  "computronica",
  "cyber diva",
  "dadabots",
  "deep beats",
  "digital dreamers",
  "digital pulse",
  "dj neural",
  "echo",
  "electra heart ai",
  "ember wave",
  "endel",
  "ether",
  "evoke music",
  "fake drake",
  "flux pavilion ai",
  "futureverse",
  "ghostwriter",
  "ghostwriter977",
  "glitch mob ai",
  "harmony ai",
  "heartstrings ai",
  "holly herndon ai",
  "infinite loop",
  "jukebox radio",
  "kai the ai",
  "kairos",
  "lora",
  "luna echo",
  "luna pearl woolf",
  "lyra ai",
  "machine girl ai",
  "melody forge",
  "midi maestro",
  "miquela",
  "mixcraft ai",
  "mubert",
  "muse ai",
  "neon idol",
  "neural beats",
  "neural groove",
  "neural note",
  "neural rhythm",
  "neural wave",
  "nima font",
  "nomis",
  "nova ai",
  "nova nexus",
  "orbit",
  "pixel sounds",
  "pulse ai",
  "quantum choir",
  "riff ai",
  "robotic beats",
  "robo pop",
  "sable valley ai",
  "shadow cast",
  "silicon soul",
  "songr ai",
  "sonic ai",
  "sonic nexus",
  "soundraw",
  "spectrum ai",
  "starlight synth",
  "stellar",
  "synapse",
  "synth city",
  "synthetica",
  "techno titan",
  "tempo ai",
  "the ai composer",
  "the algorithm",
  "the bot band",
  "the neural ensemble",
  "tidal wave ai",
  "travis bott",
  "vocaloid",
  "vox ai",
  "wave function",
  "zero bandwidth",

  // ── From spotify-ai-blocker GitHub ────────────────────────────
  "duet ai",
  "lyric lab",
  "neural mix",
  "rhythm engine",
  "sonic studio ai",
  "synthwave ai",
  "the machine orchestra",
  "virtual vocalist",

  // ── Known Suno/Udio upload accounts ───────────────────────────
  "suno bot",
  "udio music",
  "ai cover",
  "ai covers",
  "ai music",
  "ai remix",
  "ai songs",
  "ai tracks",
  "ai generated",
  "ai generated music",
  "generated by ai",
  "made by ai",
  "created by ai",
];

/** Pre-computed set for O(1) lookups */
const AI_ARTIST_SET = new Set(AI_ARTIST_NAMES.map((n) => n.toLowerCase()));

/**
 * Patterns that strongly suggest AI-generated content when found in artist names.
 */
const AI_PATTERNS: RegExp[] = [
  /\bsuno\b/i,
  /\budio\b/i,
  /\bai\s*(generated|music|cover|remix|song)\b/i,
  /\b(generated|created|made)\s*by\s*ai\b/i,
];

/**
 * Check if an artist name matches the AI blocklist.
 * Uses exact match against known names + pattern matching.
 */
export function isBlocklistedArtist(artistName: string): boolean {
  const normalized = artistName.toLowerCase().trim();

  // Exact match
  if (AI_ARTIST_SET.has(normalized)) return true;

  // Pattern match
  for (const pattern of AI_PATTERNS) {
    if (pattern.test(normalized)) return true;
  }

  return false;
}

/**
 * Check all artists on a track against the blocklist.
 * Returns the names of matched artists.
 */
export function checkTrackBlocklist(
  artists: { name: string }[]
): { matched: boolean; matchedNames: string[] } {
  const matchedNames: string[] = [];

  for (const artist of artists) {
    if (isBlocklistedArtist(artist.name)) {
      matchedNames.push(artist.name);
    }
  }

  return {
    matched: matchedNames.length > 0,
    matchedNames,
  };
}

/**
 * Get the full blocklist for display/debugging purposes.
 */
export function getBlocklist(): string[] {
  return [...AI_ARTIST_NAMES].sort();
}

/**
 * Get total count of known AI artists in the blocklist.
 */
export function getBlocklistCount(): number {
  return AI_ARTIST_SET.size;
}
